{% set name = "nomad-schema-plugin-simulation-workflow" %}
{% set version = "1.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_schema_plugin_simulation_workflow-{{ version }}.tar.gz
  sha256: 99cc4fa65b9c0649d7985399688b6fecbb933d97dfcc0f4db59c33aba758bcc8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    - nomad-lab >=1.3.13
    - nomad-schema-plugin-run >=1.0.1
    - mdanalysis >=2.8.0,<3.0.0
    - scipy >=1.7.1
    - networkx >=2.6.3

test:
  imports:
    - simulationworkflowschema
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nomad-coe/nomad-schema-plugin-simulation-workflow
  summary: Simulation workflow schema plugin for NOMAD.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
